### PR TITLE
Maintenance

### PR DESCRIPTION
**Pull request by ncfavier**
- bump stackage resolver
- relax hlint upper bound
- fix unused import warning

Fixes the nixpkgs build

### CODE REVIEW

**Comment by ncfavier** [comment]
@dahlia could you take care of this please?

**Review by dahlia — APPROVED** [review]
Thank you!

**Comment by ncfavier** [comment]
Thanks! I think you'll have to remove the `-Werror` flags to publish a release, otherwise Hackage complains.

**Comment by ncfavier** [comment]
Any chance you could cut a new release? Or add me to the package maintainer list, I'm happy to do it. I am [ncfavier](https://hackage.haskell.org/user/ncfavier) on Hackage.

**Comment by dahlia** [comment]
@ncfavier I just released a new version! <https://hackage.haskell.org/package/html-charset-0.1.1> Thanks!

**Pull request merged**
